### ISSUE TITLE
Wrong access of username key in Class SessionTimeOutFilter.

### ISSUE THREAD

**Issue by martinlasek** [Kitefusion/play-requestfilter#1]
In your SessionTimeoutFilter Class on line 28 you try to get the value behind the key "_kitefusion.play.filter.sessionTimeOut.**username**_"

`val sessionUsernameKey: String = configuration.getString("kitefusion.play.filter.sessionTimeOut.username").get`

But in your **reference.conf** file provided per default aswell as in your **README.md** you use 
"_kitefusion.play.filter.sessionTimeOut.**usernameKey**_"

Therefor your library unfortunately wont work _out-of-the-box_ and also wont work if people try to overwrite your configuration using your **suggested** keys :)

**Comment by Kitefusion** [comment]
fixed in 6fe143e80815c8256fbfb8f7c85cafeb3dfbef43
